---  
#4. On rajoute la conf du VirtualHost
- name: Set up Apache VirtualHost
  template:
    src: "files/apache.conf.j2"
    dest: "/etc/apache2/sites-available/{{http_conf}}"
  notify: "apache restart"

# Puis on lance le reste de la conf apache
- name: Enable rewrite module
  shell: /usr/sbin/a2enmod rewrite
  notify: "apache restart"

- name: Enable new site
  shell: /usr/sbin/a2ensite {{ http_conf }}
  notify: "apache restart"