metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

setup.kibana:
        host: "https://search-elk-3osl4sdpuov2rkyejqjmcq5r74.eu-west-3.es.amazonaws.com:443/_plugin/kibana/"

output.elasticsearch:
        hosts: ["https://search-elk-3osl4sdpuov2rkyejqjmcq5r74.eu-west-3.es.amazonaws.com:443"]

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

setup.ilm.enabled: false
setup.ilm.check_exists: false
