---
- name: installing and launching metricbeat
  hosts: ec2
  become: yes
  tasks:

  - name: download merticbeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-oss-7.9.1-amd64.deb 

  - name: install metricbeat deb
    command: dpkg -i metricbeat-oss-7.9.1-amd64.deb

  - name: drop in metricbeat.yml
    copy:
      src: /home/vagrant/ansible/templates/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: enable and configure system module
    command: metricbeat modules enable system

  - name: setup metricbeat
    command: metricbeat setup

  - name: start metricbeat service
    command: service metricbeat start

  - systemd:
      name: metricbeat
      enabled: yes
      masked: no

# metricbeat -e -d "*"
